// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdFtg3Bjw9XTim1riS41GJwVxwhe5Xx4',
    appId: '1:561903312484:web:482a4e65fd3a706eadc971',
    messagingSenderId: '561903312484',
    projectId: 'housely-72956',
    authDomain: 'housely-72956.firebaseapp.com',
    storageBucket: 'housely-72956.firebasestorage.app',
    measurementId: 'G-7K1NLML26J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJzfw0oSYuy-PI6YkB5YiZzU9LbeGLFQ',
    appId: '1:561903312484:android:485eedac04b71298adc971',
    messagingSenderId: '561903312484',
    projectId: 'housely-72956',
    storageBucket: 'housely-72956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9GM1EQZIlXkTqkx7nrp4yPuE_0UPvvI',
    appId: '1:561903312484:ios:602c7f9ab4213ed9adc971',
    messagingSenderId: '561903312484',
    projectId: 'housely-72956',
    storageBucket: 'housely-72956.firebasestorage.app',
    iosBundleId: 'com.pixelforge.housely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9GM1EQZIlXkTqkx7nrp4yPuE_0UPvvI',
    appId: '1:561903312484:ios:602c7f9ab4213ed9adc971',
    messagingSenderId: '561903312484',
    projectId: 'housely-72956',
    storageBucket: 'housely-72956.firebasestorage.app',
    iosBundleId: 'com.pixelforge.housely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdFtg3Bjw9XTim1riS41GJwVxwhe5Xx4',
    appId: '1:561903312484:web:0c41c2622c4c53f4adc971',
    messagingSenderId: '561903312484',
    projectId: 'housely-72956',
    authDomain: 'housely-72956.firebaseapp.com',
    storageBucket: 'housely-72956.firebasestorage.app',
    measurementId: 'G-0HHWX9CLV8',
  );
}
